version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product-catalog-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - catalog_network

  app:
    build:
      context: ./product-catalog-app
      dockerfile: Dockerfile
    container_name: product-catalog-app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - catalog_network

volumes:
  pgdata:

networks:
  catalog_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16